apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "collector.fullname" . }}
  labels:
    {{- include "collector.labels" . | nindent 4 }}
data:
   config.yaml: |-
    ---
    logStreams:
    {{- toYaml .Values.collector.config.logStreams | nindent 4 }}
