{{- if .Values.collector.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "collector.serviceAccountName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "collector.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "collector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "collector.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
