{{- if .Values.parseable.highAvailability.enabled }}
{{- $node := .Values.parseable.nodes.ingestor }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "parseable.fullname" . }}-ingestor-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "parseable.labelsSelector" . | nindent 4 }}
spec:
  type: {{ $node.service.type }}
  ports:
    - port: {{ $node.service.port }}
      targetPort: {{ $node.port }}
      protocol: TCP
  selector:
    {{- include "parseable.ingestorLabelsSelector" . | nindent 4 }}
{{- end }}
