{{- if eq .Values.parseable.highAvailability.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "parseable.fullname" . }}-querier-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ $.Values.parseable.service.type }}
  ports:
    - port: {{ $.Values.parseable.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "parseable.querierLabelsSelector" . | nindent 4 }}
{{- end }}
