{{- if .Values.parseable.metrics.serviceMonitor.enabled }}
{{- $p := .Values.parseable }}
{{- $sm := $p.metrics.serviceMonitor }}
{{- $fullname := include "parseable.fullname" . }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullname }}
  namespace: {{ default .Release.Namespace $sm.namespace }}
  labels:
    {{- include "parseable.labels" . | nindent 4 }}
    {{- with $sm.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "parseable.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: {{ $sm.port }}
      path: {{ $sm.path }}
      interval: {{ $sm.interval }}
      {{- with $sm.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with $sm.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $sm.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
