{{- $p := .Values.parseable.nodes.standalone.persistence.staging }}
{{- if and (not .Values.parseable.highAvailability.enabled) $p.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "parseable.fullname" . }}-staging-pvc
  labels:
    {{- include "parseable.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $p.accessMode | quote }}
  resources:
    requests:
      storage: {{ $p.size | quote }}
  storageClassName: "{{ $p.storageClass }}"
{{- end }}
