# Parseable on AWS (S3), distributed mode.
parseable:
  deploymentMode: distributed
  store:
    type: s3-store
    secretName: parseable-env-secret

  distributed:
    ingestor:
      replicas: 3
      persistence:
        staging:
          storageClass: gp3
          size: 5Gi
    querier:
      persistence:
        hotTier:
          storageClass: gp3
          size: 100Gi
