# Parseable on GCP (GCS), distributed mode.
parseable:
  deploymentMode: distributed
  store:
    type: gcs-store
    secretName: parseable-env-secret
    gcsCredentials:
      secretName: parseable-gcs-key
      secretKey: key.json
      mountPath: /var/secrets/google

  distributed:
    ingestor:
      replicas: 3
      persistence:
        staging:
          storageClass: standard-rwo
          size: 5Gi
    querier:
      persistence:
        hotTier:
          storageClass: standard-rwo
          size: 100Gi
