apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "parseable.fullname" . }}
  labels:
    {{- include "parseable.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.parseable.replicaCount }}
  selector:
    matchLabels:
      {{- include "parseable.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.parseable.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "parseable.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.parseable.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "parseable.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.parseable.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.parseable.securityContext | nindent 12 }}
          image: "{{ .Values.parseable.image.repository }}:{{ .Values.parseable.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.parseable.image.pullPolicy }}
          env:
            {{- range $key, $value :=  .Values.parseable.env }}
            - name: {{ $key }}
              value: {{ tpl $value $ | quote }}
            {{- end }}
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.parseable.resources | nindent 12 }}
          volumeMounts:
          - mountPath: "/parseable/cache"
            name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir: {}
      {{- with .Values.parseable.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.parseable.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.parseable.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
