apiVersion: v1
kind: Service
metadata:
  name: {{ include "parseable.fullname" . }}
  labels:
    {{- include "parseable.labels" . | nindent 4 }}
spec:
  type: {{ $.Values.parseable.service.type }}
  ports:
    - port: {{ $.Values.parseable.service.port }}
      targetPort: 5678
      protocol: TCP
      name: parseable
  selector:
    {{- include "parseable.selectorLabels" . | nindent 4 }}
