{{- if $.Values.parseable.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "parseable.serviceAccountName" . }}
  labels:
    {{- include "parseable.labels" . | nindent 4 }}
  {{- with $.Values.parseable.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
