name: Load tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'helm/**'
      - 'assets/**'
      - '**.md'

jobs:

  docker-compose-test:
    name: Docker Compose based load tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start compose
        run: docker-compose up -f ./github/docker-compose-load.yaml --build --exit-code-from quest-load
      - name: Stop compose
        if: always()
        run: docker-compose down -f ./github/docker-compose-load.yaml
