name: Integration

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "helm/**"
      - "assets/**"
      - "**.md"

jobs:
  fmt:
    name: Rust fmt and clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "target-cache"
      - run: rustup component add rustfmt clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "target-cache"
      - uses: actions-rs/cargo@v1
        with:
          command: test

  docker-compose-test:
    name: Quest Smoke and Load Tests for Standalone deployments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "target-cache"
      - name: Start compose
        run: docker compose -f docker-compose-test.yaml up --build --exit-code-from quest
      - name: Stop compose
        run: docker compose -f docker-compose-test.yaml down

  docker-compose-distributed-test:
    name: Quest Smoke and Load Tests for Distributed deployments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "target-cache"
      - name: Start compose
        run: docker compose -f docker-compose-distributed-test.yaml up --build --exit-code-from quest
      - name: Stop compose
        run: docker compose -f docker-compose-distributed-test.yaml down
